### PR TITLE
Add path for folders results when searching

### PR DESCRIPTION
**Pull request by Morikko**
Related to #207 

# Context

For some "generic words", the search results are not very explicit whereas it would be if the parent folder or the full path could be visible.

Even with the option which makes the path visible when you hover the mouse on the result, I ended spending too much times waiting the hover section to appear.

As I mostly do folder searches, I would prefer a faster solution. 

# Feature

- Add the folder path on the right of the folder search results with a lighter police
- Change the style to restrict to fit the 100% width body and allow to ellipsis when too long
- The path is always visible for now. But I can add an option in the search menu or in the extension preferences if necessary.

# Examples

2022-09-18_15-44 search folder path ex1

2022-09-18_15-44 search folder path ex1 shrink mode

2022-09-18_15-44 search folder path ex3

### CODE REVIEW

**Comment by aaFn** [comment]
Hello @Morikko , nice ! Thanks for the work, and for the suggestion.

As I see some possible side-effects on the main table, I prefer to limit this to the results table. Also, this requires a few adaptations to work well with other themes where colors are not just white-ish and black-ish ..

=> Can you give me push access on https://github.com/Morikko/Bookmark-search-plus-2/tree/search-folders-add-path so that I can place there slightly adapted versions I made, and then you can verify ?
And if/when ok with you, then I will accept your pull request with these modifications, and merge it into my repo.

**Comment by Morikko** [comment]
> Also, this requires a few adaptations to work well with other themes where colors are not just white-ish and black-ish ..

Maybe opacity would be better than grey then.

I invited you on the repo.

**Comment by aaFn** [comment]
Thank you. Yep, this is what I did. Check the files / modifications I made.

**Comment by Morikko** [comment]
Great !

2022-09-18_15-44 search folder path less padding

2022-09-18_15-44 search folder path align left

I have the feeling that the `padding-left: 10%` is a bit too much, and it will waste too much space. What about reducing to `6px` like on the screenshots above ?

Also, I have the impression that aligning at the start is better for readability (especially with the default path behavior, eg not reverse). What do you think ?

**Comment by aaFn** [comment]
I personally prefer the alignment on right as you initially did, that makes a better distinction.

10% might be a bit much yes .. but 6px seems too low ... something in between ?

**Comment by Morikko** [comment]
Okay let's keep right alignment now. We can try with 10px.

**Comment by Morikko** [comment]
It looks like this with 10px:

2022-09-18_15-44 search folder path 10px

**Comment by aaFn** [comment]
Looks good, I uploaded then the latest with content for 2.0.111 also to avoid conflicts.
If you are ok, then I will accept the PR on the main repo, let me know.

**Comment by mzso** [comment]
From my point of view I'd rather see the whole bookmark/folder text, the space is rather limited, and I don't even have as much as on the screenshot.
The path is shown in a tooltip anyway. More than enough for me.

If there was windowed mode of BSP2, then it would be great to see the path all the time for search results.

**Comment by aaFn** [comment]
Yes, do not worry, we are not cutting / reducing the bookmark or folder text.
We are just using the space left, if any.

And yes, there is a windows mode of BSP2, by opening it in a tab (see the magnifier glass menu, or right click on the BS2 icon in the toolbar).

**Comment by Morikko** [comment]
All good, looking forward to using it!

**Comment by aaFn** [comment]
Done, 2.0.111 is out with the improvement, thank you, aaFn.

**Pull request merged**
