### PR TITLE
Add option to retain the last selected bookmark position Dev 2.0.26 -> 2.0.66

### PR DESCRIPTION
**Pull request by phmio**
Hello aaFn,
Thank you for your great work on this add-on. A such add-on was really missing to replace the "Go Parent Folder" :smirk:
In this PR, i added an option to retain the last selected bookmark position which can be restored when BSP2 is reopened. 
May be you could add that feature to your next version of BSP2?

`saveLastSelectedBN_id()` is called each time you click on a bookmark (`clickHandler()`).
I had thought to call it when closing BSP2 on the event `unload` or `beforeunload`, but as this function uses asynchronously the promise `browser.storage.local.set` , so i didn't know how to wait for the end of its execution.
I  tried "await" but its use doesn't seem possible in an `unload` or `beforeunload` function.
Do you have any idea?

### CODE REVIEW

**Comment by aaFn** [comment]
Hello @phmio, thank you much for your contribution.

However, I am not sure to accept the pulll request nor to add the feature, for the following reasons:
1. The purpose of the add-on is to mimick the native bookmark sidebar as much as possible. Improving it only with the search and show in bookmark tree features, like its ancestor Bookmark Search Plus.
2. The feature of showing the last selected bookmark when reopening doesn't exist in the native bookmark sidebar.
3. Although it may be interesting to add it, it is not realted to search, and the day we manage (let's hope ..) to have the show bookmark function in the native bookmark sidebar (https://bugzilla.mozilla.org/show_bug.cgi?id=1420246) and we can discard this add-on, it would become missing.
4. The diffs in the pull request you are making are unclear. The first commit is titled "Update to 2.0.26 from xpi source code", but obviously it already contains your proposed modifications and it is more than 2.0.26.
So it is not possible to review your particular proposition as the changes are not singled out to show what would be changing in the code (the second commit is obviously only a lot of formatting edits, and does not help on understang that either).
To get a chance, one of the commits should show only the changes for the new feature.
5. A quick scan (=> I may be wrong) through the modifications you made show a problem in case where the bookmark disappeared since last time BSP2 was run.
That will result in a `handleResultClick(undefined);`  which will end up as an exception in the code.
So it does not work.
6. The code went under a major overhaul in 2.0.27 and now this PR is conflicting and cannot be merged.

My view is that you should better submit this as an improvement request to FF to get the feature included in the native Bookmark sidebar -> https://bugzilla.mozilla.org/
When it is accepted and implemented, then we would mimick it in BSP2.

Let me know your thoughts on all the above.
Thank you, aaFn.

**Comment by phmio** [comment]
Hello,
Thank you for your answer.

Before FF 57+ I was using "Bookmarks Sidebar Scroll Retainer" add-on with the native bookmark manager (ctrl+B) which allowed to keep the position of the last selected bookmark in the sidebar. This allowed me to choose among several bookmarks of a specific folder without having to scroll back to that folder each time I closed the manager to, for example, have more space visible on my screen. 
So I thought that this feature could be useful for BSP2 because it's quite annoying to redo the search every time.

Sorry for the confusion over the PR code, but I don't have much experience on git and github.
Maybe, if I have a moment I could recreate a branch with your latest version 2.0.28 from xpi and redo my modifications, this time being careful that my atom editor doesn't delete the trailing spaces. 
I suppose I should do another PR?

Regarding `handleResultClick(undefined) ;`  you're right this could cause an error,  but in the debug console I don't see anything.
I think it's because of the test you have done in handleResultClick's code `if (srcRow != undefined) {...}`

I don't think I will submit this as an improvement request to the FF team,... since I use FF the bookmark manager hasn't really evolved and it's a pity, it seems to me that it's not their priority, fortunately there are devs like you who do the job.

Again tank's for your work.

**Comment by aaFn** [comment]
Hello @phmio , we might consider creating an option for this ... will have to think about it. Then this is not a default behavior, and only people who want that would activate it, making it clear this is not a standard behavior ?

**Comment by phmio** [comment]
Hi @aaFn 
Yes, in the submitted PR branch code [dev-2.0.26](https://github.com/phmio/Bookmark-search-plus-2/archive/dev-2.0.26.zip) i have added that feature as an option `retainlastselectedbook_option` that could be activated or not.

image

Otherwise, all the stuff i have added is enclose with `// ####` in files : 
- panel.js
- option.js
- options.html, inside that file i simply added this code:
```html
    <br>
    <input type="checkbox" id="retainlastselectedbook">
    <label for="retainlastselectedbook">Retain last selected bookmark position.</label>
```

**Comment by aaFn** [comment]
Hello @phmio , coming back on this.
To implement it, I will have to reject that PR since it has too many conflicts.
I would then open an issue to point at this PR (or you can do it), to track your demand, and implement in it the latest code.

However, there are some things to decide first =
- BSP2 is made to function in multiple FF windows.
In case of such multiple windows, each time one bookmark is selected in any of the windows, the remembered value being unique will serve to all other windows .. would that be ok ?
- What to do in case a bookmark is selected during a search, but is in fact hidden (one of its parent folder is closed) ? What you propose in the PR forces it open and unhidden on next time the add-on is open. However, when you cancel the active search, it becomes hidden again .. so that wouldn't be consistent, because next add-on restart would reopen the folder while the user left it closed when stopping the add-on ..

**Comment by aaFn** [comment]
I implemented the function in 2.0.66.

As there were too many conflicts in this pull request, and anyway it was hard to see what really changed since its deltas to the base were polluted by a large number of things like space conversion/removal + several versions overwriting the inital one, there was no way to reuse any of this, except by spedning lots of hours to desintricate things ..

No time for that, so I am overwriting all the contents of this pull request with latest version of files, and then using that pull request to upload the latest version, aaFn.

**Pull request closed without merging**
